### ISSUE TITLE
View goes black when zooming, can't return

### ISSUE THREAD

**Issue by BossensM** [iTowns/itowns#1249]
When trying out the below example, if you zoom in to the point cloud and zoom until you go "through it", the whole view becomes black. There is no way to get out of it, eg when zooming out, it remains black.

http://www.itowns-project.org/itowns/examples/#pointcloud_3d_map

I think it has to do something with the view controls minDistance that is being set to 0. I have tried changing it to higher values, which eventually prevents you from scrolling through it. But I think it should be possible to scroll through this kind of objects.

**Comment by gchoqueux** [comment]
Hello, thanks. 
fixed #1253

**Comment by lc-guy** [comment]
Hello,
seems like this is still an issue, despite hardcoding the minimum distance in the examples. It would be great to avoid the issue altogether even when zooming through objects.
Could it be linked to a division by zero on ground level erroring out the zoom to NaN or something like that...?

**Comment by mgermerie** [comment]
> Hello, seems like this is still an issue, despite hardcoding the minimum distance in the examples. It would be great to avoid the issue altogether even when zooming through objects. Could it be linked to a division by zero on ground level erroring out the zoom to NaN or something like that...?

Hi @lc-guy,
I added a fix in #1722 for a "black screen bug" when zooming while no object is under the screen center. Could you please let me know if this fixes the issue you had ?
