### ISSUE TITLE
view.pickFeaturesAt not working for GeometryLayer in Angular app

### ISSUE THREAD

**Issue by iamthechad** [iTowns/itowns#1363]
## Your Environment

* Version used: 2.15.0 (can't upgrade beyond this right now for various reasons)
* Browser Name and version: Chrome/Firefox latest
* Operating System and version (desktop or mobile): MacOS, Windows 10
* Link to your project: Reproducible project -> https://angular-scuijt.stackblitz.io

## Context
I have an Angular project that wraps itowns. I've been able to successfully add a `GeometryLayer` with GeoJSON as the source (both from a `FileSource` and `WFSSource`). I need to display information about features when a user moves their mouse over the feature. For some reason, I am completely unable to get `view.pickFeaturesAt` working. I also have the same issue with `view.pickObjectsAt`.

For what it's worth, we have another layer that's a `ColorLayer` and `view.pickFeaturesAt` works correctly for it.

## Steps to Reproduce (for bugs)
1. Open the sample project at https://angular-scuijt.stackblitz.io
2. Open the console area to see console messages
3. Move the mouse over either of the two shapes
4. Observe that the console messages do not contain any information even when the mouse is over a shape. (The console messages are just dumping the return value of `view.pickFeaturesAt`)

## Expected Behavior
`view.pickFeaturesAt` should return information when the mouse is over a shape on the `GeometryLayer`

## Actual Behavior
No information is returned from `view.pickFeaturesAt` for shapes added onto a `GeometryLayer`

## Possible Cause/Fix/Solution
I don't know if this may have something to do with Angular or not. 

I can see the correct behavior in the examples on the itowns website. 

I've spent quite a while debugging into the source, but I don't have a good idea of where things are breaking down.

**Comment by zarov** [comment]
Thanks for the detailed issue !

I know you are sticking to 2.15.0, but is there any chance you could update to 2.15.3 ? We missed a few bugs concerning coordinates conversion when doing the 2.15.0 release, and they were fixed in 2.15.3. This should resolve your problem.

**Comment by iamthechad** [comment]
Sadly, switching to 2.15.3 doesn't seem to make a difference.

The StackBlitz example is actually running 2.20.0, so this issue is still present even in the latest.

Here's a better link for the example: https://stackblitz.com/edit/angular-scuijt

**Comment by zarov** [comment]
Indeed it does not make it work. After a few looks at it, I can say that the documentation is misleading: `view.pickFeaturesAt` does not work with a `GeometryLayer`. However, you can use `view.pickObjectsAt` to achieve the wanted result. Let me know if it works for you !

I'm updating the documentation in the same time

**Comment by iamthechad** [comment]
`view.pickObjectsAt` seems to do what I need. Thanks for the quick reply!

**Comment by zarov** [comment]
No problem !
