### ISSUE TITLE
Modifiying the visibility/opacity of a pointcloud class is affecting the other classes

### ISSUE THREAD

**Issue by AnthonyGlt** [iTowns/itowns#2540]
## Context
I'm using the classification view of a cloud point. When I'm editing the value of opacity of one class, other classes are impacted and I can see through other points

## Steps to Reproduce

1. Edit the opacity of a class in the DEFAULT ClassificationScheme of PointsMaterial.js . For example, opacity 0.0 in the "building" class
2. Load Sete point cloud from the 3dtiles_loader.html
3. Switch to classification view
4. Observe that the transparency is applied also tho other points

## Expected Behavior
Just hide the specified class

## Actual Behavior
Other classes are impacted

![Image](https://github.com/user-attachments/assets/13c6e8e3-0727-49dd-9eb0-ba6fe3c53683)

**Comment by AnthonyGlt** [comment]
@ftoromanoff  Could this [MR](https://github.com/iTowns/itowns/pull/2374) fix this issue ? WDYT ?

**Comment by ftoromanoff** [comment]
It fixes the probleme for PointCloudLayer, 3Dtiles works a bit differently I think but if it's based on the same PointMaterial, it should fix the probleme as well.

**Comment by ftoromanoff** [comment]
I added a commit #2374 to report the changes I made on PointCloudLayer to 3DTilesLayer.
1) Set transparency at true by default (https://github.com/iTowns/itowns/pull/2374/commits/cf203c572c52025e94a5a6f5b6914876cc46dba7)
2) add the properties depthWrite (https://github.com/iTowns/itowns/pull/2374/commits/1e34e24e437127126086acd8bc00b05d4ba16949)

Does this help you with the issue, or at least help you find a solution in your case ? (I havn't check performances as well)

**Comment by AnthonyGlt** [comment]
@ftoromanoff With your modifications, it looks like the issue has been solved !
Thank you

**Comment by AnthonyGlt** [comment]
fixed by
https://github.com/iTowns/itowns/pull/2374

**Comment by jailln** [comment]
Reopen: the fix was rolled back in #2584

**Comment by ftoromanoff** [comment]
I confirm that one of my bug is back as well.
Using the class visibility change the color of the point to 'white' and not to transparent:

With the points classified as 'default':
<img width="1266" height="913" alt="Image" src="https://github.com/user-attachments/assets/5baa9890-831b-48d0-8778-6d5a09129378" />

Without them:
<img width="1284" height="897" alt="Image" src="https://github.com/user-attachments/assets/9214f03f-19fb-405c-be41-31321b1faa44" />

Example:
http://localhost:8080/examples/copc_simple_loader.html?copc=https://s3.amazonaws.com/data.entwine.io/millsite.copc.laz&mode=3
