### ISSUE TITLE
Potree2 PointCloud doesn't appear with PlanarView

### ISSUE THREAD

**Issue by ketourneau** [iTowns/itowns#2633]
Since https://github.com/iTowns/itowns/pull/2498

Potree2 point clouds no longer appear with PlanarView.

Source code : https://github.com/bloc-in-bloc/itowns/blob/f/potree2-planarView-bug/examples/view_25d_map.html#L108

Before https://github.com/iTowns/itowns/pull/2498
<img width="1417" height="771" alt="Image" src="https://github.com/user-attachments/assets/55573f43-2e92-4d80-9356-0923f580b557" />

After https://github.com/iTowns/itowns/pull/2498
<img width="1251" height="779" alt="Image" src="https://github.com/user-attachments/assets/413cb36c-94be-4bcb-9512-ca66c7805082" />

**Comment by ftoromanoff** [comment]
I indeed forgot to update the Potree2BrotliLoader...
I open a PR #2635 to correct this oversight.

<img width="861" height="779" alt="Image" src="https://github.com/user-attachments/assets/e42b66b9-37d1-41c6-babc-ffd42f407a58" />


A refactorization between the commun part of the 2 Potree2Loader, should be done, to avoid similar oversight later on...

**Comment by ftoromanoff** [comment]
The PR #2635 fixing this had been merged into master. Can you confirme that the bug is fixed ? @ketourneau Thanks in advance !

**Comment by ketourneau** [comment]
Thanks for the fix ! It's work now in the simple example but it still doesn't work in our use case (custom controls, custom renderer, custom camera) https://github.com/bloc-in-bloc/itowns/blob/f/custom-pointcloud-sample/examples/demo_hackathon_orvault_planarView.html

**Comment by ketourneau** [comment]
On master branch (demo_hackathon_orvault_planarView.html) :
<img width="1916" height="932" alt="Image" src="https://github.com/user-attachments/assets/0348a53b-92a5-4e15-90b8-dba97d05f46c" />

Before the changes on point cloud (demo_hackathon_orvault_planarView.html) :
<img width="1914" height="931" alt="Image" src="https://github.com/user-attachments/assets/74860726-56a3-4933-9257-9577ac63136d" />

**Comment by ftoromanoff** [comment]
From what I started to check, it's a problem with the matrixWorld of the camera3D of the custom camera.
The update loop calculate that the bbox of the node are not in the cameraSpace...
https://github.com/iTowns/itowns/blob/628f03ec1fe0b7953996c4728eb8c62a2e73c15e/packages/Main/src/Renderer/Camera.js#L230

**Comment by ketourneau** [comment]
How could it work before changes on pointcloud ?

**Comment by ftoromanoff** [comment]
Before the changes the crs was not at all taking into account... meaning that whatever crs you was saying the data were considered as in the default crs, and everthing else was considered in the same crs. Now the crs is really considered from pointCloudData, and we need to be sure that your custom camera is well defined in the data crs.

**Comment by ketourneau** [comment]
@ftoromanoff How I can help you to debug ?

**Comment by ftoromanoff** [comment]
This example uses a custom Camera and a custom Renderer. It seems pretty complex for me and it's hard to understand was is the purpose of it.. I will advice to start again from a basic example and add little by little the different aspects of what you want to show in your example. With this approach you might find where exactly the bug appears... As the basic example seems to work fine, it might not directly be the reprojection that causes the bug...

**Comment by ketourneau** [comment]
Ok, thanks for the reply. I'll try starting again from the basic example with just a custom camera for debuging (without custom renderer).

**Comment by ketourneau** [comment]
I have updated our custom sample which reproduce the problem : https://github.com/bloc-in-bloc/itowns/commit/73ea8b37fea8786d1aa4f320d6c65b0c2f5aa923

After analysis with @ftoromanoff there seems to be a problem with the matrix world of clampOBB used to determine if element is visible in [PointCloudLayer](https://github.com/iTowns/itowns/blob/master/packages/Main/src/Layer/PointCloudLayer.js#L360).

A little more explanation about our use case : We need to place the itowns Planar View to a specific position because we display georeferenced data outside itowns context.
The ThreeJS scene center (0,0,0) must match the georeferenced BBOX center. So we must apply an "offset" (position and rotation) to the itowns planar view (by object3d parameter) to match our system.

```
iTownsViewRoot => offset position
└─ pivot => offset rotation, passed to PlanarView as object3D parameter
    └─ PointCloudGroup => Passed to Potree2Layer as object3D parameter
```

Does anyone have any idea how to take into account object3D parameter to correctly rendering point cloud since #2498 ? More specifically, I notice a breaking (for our use case) since this [commit](https://github.com/iTowns/itowns/commit/77163e38e0f9f5019e8efb1c2c2b83665664410f).

**Comment by ftoromanoff** [comment]
@ketourneau 
Can you try #2656 ?

**Comment by ftoromanoff** [comment]
@ketourneau I did finalized the PR #2656 fixing this issue. Can you ty it on your side to see if everything works as expected?

**Comment by ketourneau** [comment]
It works perfectly for our use case ! Thanks for the fix  !
